### PR TITLE
updated packages

### PR DESCRIPTION
**Pull request by ShiboSoftwareDev**

### CODE REVIEW

**Review by seveibar — COMMENTED** [review]
Hmm, why are the 0402s broken? I feel like we should fix that issue before updating snapshots to at least make it clear these worked

**Comment by ShiboSoftwareDev** [comment]
@seveibar I can't figure out why this test failed on pr and not locally

**Comment by seveibar** [comment]
@ShiboSoftwareDev looks like a timeout, should we increase the action timeout?

**Comment by seveibar** [comment]
or is it infinite looping on ci?

**Comment by ShiboSoftwareDev** [comment]
> or is it infinite looping on ci?

only on ci yes

**Comment by seveibar** [comment]
@ShiboSoftwareDev this could be related to the schematic trace infinite loop errors, if we fix the issue that's causing schematic traces to enter an infinite loop we could fix this upgrade issue

it would be nice to disable schematic rendering altogether as well, this would also be useful generally because we could optimize snippets/cli to only render the required view.

we could implement `root.schematicDisabled` then have the property defined on the root circuit?

**Comment by ShiboSoftwareDev** [comment]
@seveibar then pass this as a prop to a component to prevent generating the schematic?

**Review by seveibar — COMMENTED** [review]
This is still timing out even after disabling schematic rendering? Maybe we need to log using circuit.on(“anyRenderEvemt”) to figure out what phase or element is the issue (cant remember the exact event name)

/bounty $20

**Comment by ShiboSoftwareDev** [comment]
@seveibar I changed the seed circuit of the test, I need this repo to be updated asap. Should I make a reproduction of the error and skip the test so we can solve the problem later?

**Review by seveibar — APPROVED** [review]
@ShiboSoftwareDev sounds like a plan!

**Pull request merged**
